---
- name: Copy backup script
  become: true
  template:
    src: templates/{{ item.src }}
    dest: /usr/local/bin/{{ item.dest }}
    mode: 0740
  with_items:
    - {'src': 'backup.sh.j2', 'dest': '/usr/local/bin/misp_backup'}
    - {'src': 'restore.sh.j2', 'dest': '/usr/local/bin/misp_restore'}

- name: Create backup cronjob
  cron:
    name: "misp backup cronjob"
    state: present
    minute: "0"
    hour: "4"
    job: "sh /usr/local/bin/misp_backup"
