---
- name: Check MISP worker launcher permissions
  file:
    path: /opt/misp/app/Console/worker/start.sh
    owner: "{{ misp_user }}"
    group: "{{ misp_group }}"
    mode: 0764

- name: Check MISP worker autolaunch at boot
  lineinfile:
    state: present
    dest: /etc/rc.local
    insertbefore: "exit 0"
    line: "sudo -u www-data bash /opt/misp-server/misp/app/Console/worker/start.sh"
