---
dependency:
  name: galaxy
  options:
    ignore-certs: true
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml_lint.yml
platforms:
  - name: instance
    image: ansible/ansible:ubuntu1604py3
    # command: apt-get install python3.6
    # privileged: true
    # pull: true
    # pre_build_image: true
provisioner:
  name: ansible
  options:
    vv: true
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 120
